### ISSUE TITLE
[BUG] 安卓12崩溃

### ISSUE THREAD

**Issue by damieai** [luckyzyx/LuckyTool#16]
崩溃信息:
Launcher activity not found for package com.luckyzyx.luckytool
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:215)
	at com.android.server.pm.ShortcutService.fillInDefaultActivity(ShortcutService.java:1929)
	at com.android.server.pm.ShortcutService.lambda$setDynamicShortcuts$5$ShortcutService(ShortcutService.java:1980)
	at com.android.server.pm.ShortcutService$$ExternalSyntheticLambda10.run(Unknown Source:12)
	at com.android.server.pm.ShortcutService.injectPostToHandlerIfAppSearch(ShortcutService.java:1765)

类名:null

方法:null

行数:0

类型:null

时间:2023-02-04_13:45

设备名称:RMX2121

设备厂商:realme

系统版本:Android 12-31

CPU-ABI:arm64-v8a

versionCode:null

versionName:null

全部信息:
null

**Comment by luckyzyx** [comment]
> 崩溃信息:
> Launcher activity not found for package com.luckyzyx.luckytool
> 	at com.android.internal.util.Preconditions.checkState(Preconditions.java:215)
> 	at com.android.server.pm.ShortcutService.fillInDefaultActivity(ShortcutService.java:1929)
> 	at com.android.server.pm.ShortcutService.lambda$setDynamicShortcuts$5$ShortcutService(ShortcutService.java:1980)
> 	at com.android.server.pm.ShortcutService$$ExternalSyntheticLambda10.run(Unknown Source:12)
> 	at com.android.server.pm.ShortcutService.injectPostToHandlerIfAppSearch(ShortcutService.java:1765)
> 
> 类名:null
> 
> 方法:null
> 
> 行数:0
> 
> 类型:null
> 
> 时间:2023-02-04_13:45
> 
> 设备名称:RMX2121
> 
> 设备厂商:realme
> 
> 系统版本:Android 12-31
> 
> CPU-ABI:arm64-v8a
> 
> versionCode:null
> 
> versionName:null
> 
> 全部信息:
> null

需提供复现录屏等信息
[点击前往TG讨论群反馈](https://t.me/+F42pfv-c0h4zNDc9)
